In [35]:
import pandas as pd 

# FolderPath = "/content/drive/MyDrive/Colab Notebooks/PDU"
FilePath = "OLD\\FinalLabelDataAll.csv"
# /content/drive/MyDrive/Colab Notebooks/PDU/FinalLabelDataAll.csv
Raw_DB = pd.read_csv(FilePath)
Raw_DB.head()

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (150,151,152) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,dt,wid,sid,recid,seqid,date,time,actcode,blockpos,...,spare_5,spare_6,spare_7,spare_8,spare_9,spare_10,label,LABEL_ConnectionActivity,LABEL_SubActivity,LABEL_Activity
0,0,2021-04-26 10:45:28,143,0,1,32767,2021-04-26,10:45:28,2,4.33,...,0.0,0.0,0.0,63.79,0.0,0.0,NaN,NaN,NaN,NaN
1,1,2021-04-26 10:45:33,143,0,1,32767,2021-04-26,10:45:33,2,4.33,...,0.0,0.0,0.0,63.79,0.0,0.0,NaN,NaN,NaN,NaN
2,2,2021-04-26 10:46:36,143,0,1,32767,2021-04-26,10:46:36,2,4.33,...,0.0,0.0,0.0,63.79,0.0,0.0,NaN,NaN,NaN,NaN
3,3,2021-04-26 10:46:41,143,0,1,32767,2021-04-26,10:46:41,2,4.33,...,0.0,0.0,0.0,63.79,0.0,0.0,NaN,NaN,NaN,NaN
4,4,2021-04-26 10:46:46,143,0,1,32767,2021-04-26,10:46:46,2,4.33,...,0.0,0.0,0.0,63.79,0.0,0.0,NaN,NaN,NaN,NaN

In [37]:
# for i in Raw_DB.columns:
#     print(i)

TimebasedCol = [
    "dt",
    "date",
    "time"
]
ListUsedCol = ["bitdepth",
            "md",
            "blockpos",
            "rop",
            "hklda",
            "woba",
            "torqa",
            "rpm",
            "stppress",
            "mudflowin"]

LabelCol = ["LABEL_ConnectionActivity",
            "LABEL_SubActivity",
            "LABEL_Activity"]
        
finalUsedCol = TimebasedCol + ListUsedCol + LabelCol
finalUsedCol

['dt',
 'date',
 'time',
 'bitdepth',
 'md',
 'blockpos',
 'rop',
 'hklda',
 'woba',
 'torqa',
 'rpm',
 'stppress',
 'mudflowin',
 'LABEL_ConnectionActivity',
 'LABEL_SubActivity',
 'LABEL_Activity']

In [38]:
Used_DB = Raw_DB[finalUsedCol]
Used_DB[LabelCol[0]] = Used_DB[LabelCol[0]].str.upper()
Used_DB[LabelCol[1]] = Used_DB[LabelCol[1]].str.upper()
Used_DB[LabelCol[2]] = Used_DB[LabelCol[2]].str.upper()

Used_DB["LABEL_SubActivity"] = Used_DB["LABEL_SubActivity"].str.replace('REAMING ', 'REAMING', regex=False)

Used_DB

C:\Users\irsya\AppData\Local\Temp/ipykernel_30052/1755080858.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Used_DB[LabelCol[0]] = Used_DB[LabelCol[0]].str.upper()
C:\Users\irsya\AppData\Local\Temp/ipykernel_30052/1755080858.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Used_DB[LabelCol[1]] = Used_DB[LabelCol[1]].str.upper()
C:\Users\irsya\AppData\Local\Temp/ipykernel_30052/1755080858.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Used_DB[LabelCol[2]] = Used_DB[LabelCol[2]].str.upper()
C:\Users\irsya\AppData\Local\Temp/ipykernel_30052/1755080858.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Used_DB["LABEL_SubActivity"] = Used_DB["LABEL_SubActivity"].str.replace('REAMING ', 'REAMING', regex=False)

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,LABEL_ConnectionActivity,LABEL_SubActivity,LABEL_Activity
0,2021-04-26 10:45:28,2021-04-26,10:45:28,62.7,62.70,4.33,2.83,41.21,17.33,5.0,49.0,637.5,1024.27,NaN,NaN,NaN
1,2021-04-26 10:45:33,2021-04-26,10:45:33,62.7,62.70,4.33,2.83,41.21,17.33,5.0,49.0,637.5,1024.27,NaN,NaN,NaN
2,2021-04-26 10:46:36,2021-04-26,10:46:36,62.7,62.70,4.33,2.83,41.21,17.33,5.0,49.0,637.5,1024.27,NaN,NaN,NaN
3,2021-04-26 10:46:41,2021-04-26,10:46:41,62.7,62.70,4.33,2.83,41.21,17.33,5.0,49.0,637.5,1024.27,NaN,NaN,NaN
4,2021-04-26 10:46:46,2021-04-26,10:46:46,62.7,62.70,4.33,2.83,41.21,17.33,5.0,49.0,637.5,1024.27,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579286,2021-06-03 10:17:51,2021-06-03,10:17:51,0.0,0.01,25.13,0.00,29.93,0.00,0.0,0.0,0.0,0.00,NaN,NaN,NaN
579287,2021-06-03 10:17:56,2021-06-03,10:17:56,0.0,0.01,25.13,0.00,29.93,0.00,0.0,0.0,0.0,0.00,NaN,NaN,NaN
579288,2021-06-03 10:18:01,2021-06-03,10:18:01,0.0,0.01,25.13,0.00,29.94,0.00,0.0,0.0,0.0,0.00,NaN,NaN,NaN
579289,2021-06-03 10:18:06,2021-06-03,10:18:06,0.0,0.01,25.13,0.00,29.93,0.00,0.0,0.0,0.0,0.00,NaN,NaN,NaN
579290,2021-06-03 10:18:11,2021-06-03,10:18:11,0.0,0.01,25.13,0.00,29.93,0.00,0.0,0.0,0.0,0.00,NaN,NaN,NaN

In [39]:
start_time = "4/26/2021 12:56:00"
end_time = "23/05/2021 00:55"

start_time = "2021-05-11 03:10:00"
end_time = "2021-05-23 00:55:00"



idx_logic = (Used_DB["dt"] >= start_time) &  (Used_DB["dt"] <= end_time)
FinalUsed_DB = Used_DB.loc[idx_logic, :]
FinalUsed_DB

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,LABEL_ConnectionActivity,LABEL_SubActivity,LABEL_Activity
238414,2021-05-11 03:10:03,2021-05-11,03:10:03,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
238415,2021-05-11 03:10:08,2021-05-11,03:10:08,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
238416,2021-05-11 03:10:13,2021-05-11,03:10:13,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
238417,2021-05-11 03:10:18,2021-05-11,03:10:18,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
238418,2021-05-11 03:10:23,2021-05-11,03:10:23,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427358,2021-05-23 00:54:40,2021-05-23,00:54:40,9.21,2172.06,5.13,0.0,29.42,0.0,0.0,0.0,0.0,0.0,NO DATA,MAKE UP BHA,MAKE UP BHA
427359,2021-05-23 00:54:45,2021-05-23,00:54:45,9.21,2172.06,5.13,0.0,29.36,0.0,0.0,0.0,0.0,0.0,NO DATA,MAKE UP BHA,MAKE UP BHA
427360,2021-05-23 00:54:50,2021-05-23,00:54:50,9.21,2172.06,5.13,0.0,29.36,0.0,0.0,0.0,0.0,0.0,NO DATA,MAKE UP BHA,MAKE UP BHA
427361,2021-05-23 00:54:55,2021-05-23,00:54:55,9.21,2172.06,5.13,0.0,29.36,0.0,0.0,0.0,0.0,0.0,NO DATA,MAKE UP BHA,MAKE UP BHA
427362,2021-05-23 00:55:00,2021-05-23,00:55:00,9.21,2172.06,5.13,0.0,29.36,0.0,0.0,0.0,0.0,0.0,NO DATA,MAKE UP BHA,MAKE UP BHA

In [41]:
# Label the drill vs trip data
list_start_time = []
list_end_time = []


list_start_time.append("2021-05-12 15:03:40")
list_end_time.append("2021-05-15 2:41:33")
list_start_time.append("2021-05-15 19:29:28")
list_end_time.append("2021-05-17 17:26:01")
list_start_time.append("2021-05-17 21:53:01")
list_end_time.append("2021-05-19 21:37:21")


FinalUsed_DB.loc[:, "LABEL_MajorActivity"] = "Tripping"

for start_temp,end_temp in zip(list_start_time, list_end_time):

    idx_logic = (Used_DB["dt"] >= start_temp) &  (Used_DB["dt"] <= end_temp)
    FinalUsed_DB.loc[idx_logic, "LABEL_MajorActivity"] = "Drilling"
    print(start_temp)
    print(end_temp)

2021-05-12 15:03:40
2021-05-15 2:41:33
2021-05-15 19:29:28
2021-05-17 17:26:01
2021-05-17 21:53:01
2021-05-19 21:37:21

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [44]:
FinalUsed_DB.to_csv("RealTime_Test\\AAE-03_RAW.csv")

In [95]:
LabelTest = pd.read_excel("sorik\\CompileLabel_AAE3.xlsx", sheet_name="AAE-3")
LabelTest

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Connection Activity,Sub Activity,Activity,MajorActivity
0,2021-04-26,12:56:00,2021-04-26 12:56:00,NaN,NaN,NaN,0.00,,,,NaN,NaN,NaN,NaN,NaN,NaN,Tripping
1,2021-05-11,00:00:00,2021-05-11 00:00:00,570.000000,343.00,0.0,0.00,,,,NaN,NaN,NaN,NaN,Other,Other,Tripping
2,2021-05-11,09:30:00,2021-05-11 09:30:00,210.000000,343.00,NaN,1.04,,,,NaN,NaN,NaN,NaN,Other,Other,Tripping
3,2021-05-11,13:00:00,2021-05-11 13:00:00,190.000000,343.00,NaN,0.00,,,,NaN,NaN,NaN,NaN,Other,Other,Tripping
4,2021-05-11,16:10:00,2021-05-11 16:10:00,131.000000,343.00,NaN,12.65,,,,NaN,NaN,NaN,NaN,Make Up BHA,Make up BHA,Tripping
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,2021-05-22,21:50:20,2021-05-22 21:50:20,0.666667,2172.06,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Moving,Other,Tripping
1696,2021-05-22,21:51:00,2021-05-22 21:51:00,46.000000,2172.06,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Other,Other,Tripping
1697,2021-05-22,22:37:00,2021-05-22 22:37:00,92.000000,2172.06,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Other,Other,Tripping
1698,2021-05-23,00:09:00,2021-05-23 00:09:00,46.000000,2172.06,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Make Up BHA,Make up BHA,Tripping
1699,2021-05-23,00:55:00,2021-05-23 00:55:00,NaN,2172.06,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Make Up BHA,Make up BHA,Tripping

In [96]:
import numpy as np
DrillingOnlyDB = LabelTest[LabelTest["MajorActivity"]=="Drilling"]
DrillingOnlyDB
start_idx = DrillingOnlyDB.index.values[0]
print(start_idx)
LabelTest['ConnectionTime_Test'] = np.nan

for i,row in DrillingOnlyDB[DrillingOnlyDB['Connection Activity'].isin(['Connection', "Post Connection"])].iterrows():
    if row['Connection Activity'] == 'Connection':
        end_idx = i-1
        print(str(start_idx) + " - " + str(end_idx))
        print(LabelTest.loc[start_idx:end_idx, "Meterage (m) (Drilling)"].fillna(0))
        print('tes')
        print(LabelTest.loc[start_idx:end_idx, "Meterage (m) (Drilling)"].fillna(0).sum())
        # break
        LabelTest.loc[i, "Meterage (m) (Drilling)_Test"] = LabelTest.loc[start_idx:end_idx, "Meterage (m) (Drilling)"].fillna(0).sum()
    elif row['Connection Activity'] == 'Post Connection':
        start_idx = i

102
102 - 110
102     4.35
103     0.00
104     0.00
105     0.00
106     0.00
107     0.00
108     0.00
109    25.82
110     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
30.170000000000073
112 - 118
112     0.00
113     2.12
114     0.00
115     7.70
116     0.00
117    19.70
118     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.519999999999982
120 - 137
120     0.00
121    15.92
122     0.00
123     0.00
124     0.00
125     0.00
126     0.00
127     0.00
128     0.00
129     0.00
130     0.00
131     0.00
132     0.00
133     0.00
134     0.00
135     0.00
136    13.49
137     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.409999999999854
139 - 149
139     0.00
140     2.19
141     0.00
142     4.00
143     0.00
144     1.02
145     0.00
146     2.49
147     0.00
148    19.79
149     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.49000000000001
151 - 157
151     0.0
152     2.7
153     0.0
154     9.0
155     0.0
156    17.2
157     0.0
Name: Meterage (m) (Drilling), dtype: float64
tes
28.90000000000009
159 - 167
159     0.00
160     4.00
161     0.00
162     4.64
163     0.00
164     6.41
165     0.00
166    15.45
167     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
30.5
169 - 171
169     0.00
170    29.04
171     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.039999999999964
173 - 175
173     0.00
174    29.92
175     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.920000000000073
177 - 179
177     0.00
178    29.39
179     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.389999999999873
181 - 183
181     0.00
182    29.22
183     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.220000000000027
185 - 213
185     0.00
186    25.23
187     0.00
188     0.00
189     0.00
190     0.00
191     0.00
192     0.00
193     0.00
194     0.00
195     0.00
196     0.00
197     0.00
198     0.00
199     0.00
200     0.00
201     0.00
202     0.00
203     0.00
204     0.00
205     0.00
206     0.00
207     0.00
208     0.00
209     0.00
210     0.00
211     0.00
212     4.42
213     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.65000000000009
215 - 217
215     0.00
216    29.01
217     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.00999999999999
219 - 221
219     0.00
220    29.47
221     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.470000000000027
223 - 225
223     0.00
224    29.89
225     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.889999999999873
223 - 428
223     0.00
224    29.89
225     0.00
226    29.89
227     0.00
       ...
424     0.00
425     0.00
426     0.00
427     0.00
428     0.00
Name: Meterage (m) (Drilling), Length: 206, dtype: float64
tes
59.779999999999745
430 - 436
430     0.00
431    12.33
432     0.00
433    10.42
434     0.00
435     7.26
436     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
30.00999999999999
438 - 442
438     0.00
439     5.76
440     0.00
441    23.41
442     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.170000000000073
444 - 454
444     0.00
445     2.74
446     0.00
447     2.90
448     0.00
449     2.56
450     0.00
451     0.25
452     0.00
453    21.31
454     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.75999999999999
456 - 464
456     0.00
457     4.98
458     0.00
459     2.34
460     0.00
461    17.53
462     0.00
463     4.01
464     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
28.860000000000127
466 - 484
466    0.00
467    5.12
468    0.00
469    1.50
470    0.00
471    0.71
472    0.00
473    0.13
474    0.00
475    0.46
476    0.00
477    5.20
478    0.00
479    4.09
480    0.00
481    3.90
482    0.00
483    8.42
484    0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.529999999999973
486 - 494
486     0.00
487    10.97
488     0.00
489     1.54
490     0.00
491     8.07
492     0.00
493     9.02
494     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.59999999999991
496 - 510
496     0.00
497     8.98
498     0.00
499     3.70
500     0.00
501     1.84
502     0.00
503     0.00
504     0.00
505     0.70
506     0.00
507     3.77
508     0.00
509    10.69
510     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.680000000000064
512 - 514
512     0.00
513    27.41
514     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
27.409999999999854
517 - 519
517     0.00
518    29.48
519     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.480000000000018
521 - 533
521     0.00
522    16.03
523     0.00
524     1.99
525     0.00
526     2.22
527     0.00
528     4.09
529     0.00
530     1.72
531     0.00
532     3.39
533     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.440000000000055
535 - 555
535     0.00
536     7.00
537     0.00
538     1.81
539     0.00
540     1.36
541     0.00
542     1.05
543     0.00
544     0.69
545     0.00
546     1.06
547     0.00
548     1.96
549     0.00
550     1.00
551     0.00
552     1.04
553     0.00
554    12.65
555     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.62000000000012
557 - 559
557     0.00
558    29.51
559     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.50999999999999
561 - 609
561    0.0
562    0.0
563    0.0
564    0.0
565    0.0
566    0.0
567    0.0
568    0.0
569    0.0
570    0.0
571    0.0
572    0.0
573    0.0
574    0.0
575    0.0
576    0.0
577    0.0
578    0.0
579    0.0
580    0.0
581    0.0
582    0.0
583    0.0
584    0.0
585    0.0
586    0.0
587    0.0
588    0.0
589    0.0
590    0.0
591    0.0
592    0.0
593    0.0
594    0.0
595    0.0
596    0.0
597    0.0
598    0.0
599    0.0
600    0.0
601    0.0
602    0.0
603    0.0
604    0.0
605    0.0
606    0.0
607    0.0
608    0.0
609    0.0
Name: Meterage (m) (Drilling), dtype: float64
tes
0.0
611 - 621
611     0.00
612     4.08
613     0.00
614     0.76
615     0.00
616     2.34
617     0.00
618     1.28
619     0.00
620    21.01
621     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.470000000000027
623 - 639
623     0.00
624     5.37
625     0.00
626     2.66
627     0.00
628     1.47
629     0.00
630     0.70
631     0.00
632     4.17
633     0.00
634     1.34
635     0.00
636     1.96
637     0.00
638    11.78
639     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.449999999999818
641 - 645
641     0.00
642    11.79
643     0.00
644    17.33
645     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.12000000000012
647 - 651
647     0.00
648     8.84
649     0.00
650    20.73
651     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.569999999999936
653 - 657
653     0.00
654    20.28
655     0.00
656     9.22
657     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.5
659 - 661
659     0.00
660    29.51
661     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.50999999999999
663 - 671
663     0.00
664     0.93
665     0.00
666     7.98
667     0.00
668     8.26
669     0.00
670    12.72
671     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.8900000000001
673 - 677
673     0.00
674    25.63
675     0.00
676     3.48
677     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.110000000000127
679 - 687
679     0.00
680     7.66
681     0.00
682    14.41
683     0.00
684     2.80
685     0.00
686     4.61
687     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.480000000000018
689 - 695
689     0.00
690     5.74
691     0.00
692    15.10
693     0.00
694     8.73
695     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.56999999999971
697 - 699
697     0.00
698    29.51
699     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
29.51000000000022
703 - 705
703     0.00
704    19.67
705     0.00
Name: Meterage (m) (Drilling), dtype: float64
tes
19.670000000000073

In [97]:
DrillingOnlyDB.head(20)

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Connection Activity,Sub Activity,Activity,MajorActivity
102,2021-05-12,15:03:40,2021-05-12 15:03:40,26.000000,1092.00,1092.00,4.35,00:26:00,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling
103,2021-05-12,15:29:40,2021-05-12 15:29:40,44.000000,1092.00,1092.00,0.00,,,00:44:00,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling
104,2021-05-12,16:13:40,2021-05-12 16:13:40,8.333333,1092.00,1092.00,0.00,,,,0.133333,NaN,NaN,NaN,connection,Drilling Formation,Drilling
105,2021-05-12,16:22:00,2021-05-12 16:22:00,33.666667,1092.00,1092.00,0.00,,,,NaN,NaN,NaN,NaN,Pressure Test,Drilling Formation,Drilling
106,2021-05-12,16:55:40,2021-05-12 16:55:40,84.333333,1092.00,1092.00,0.00,,,,NaN,NaN,NaN,NaN,Stationary,Stationary,Drilling
107,2021-05-12,18:20:00,2021-05-12 18:20:00,4.250000,1092.00,1092.00,0.00,,,,0.066667,NaN,NaN,NaN,connection,Drilling Formation,Drilling
108,2021-05-12,18:24:15,2021-05-12 18:24:15,13.916667,1092.06,1092.06,0.00,,,00:13:55,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling
109,2021-05-12,18:38:10,2021-05-12 18:38:10,197.000000,1117.88,1117.88,25.82,03:17:00,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling
110,2021-05-12,21:55:10,2021-05-12 21:55:10,16.750000,1117.88,1117.88,0.00,,,00:16:45,NaN,NaN,NaN,Pre connection,Reaming,Drilling Formation,Drilling
111,2021-05-12,22:11:55,2021-05-12 22:11:55,5.250000,1117.88,1117.88,25.82,,,,0.083333,03:17:00,05:47:40,Connection,connection,Drilling Formation,Drilling
112,2021-05-12,22:17:10,2021-05-12 22:17:10,4.166667,1117.88,1117.88,0.00,,,00:04:10,NaN,NaN,NaN,Post Connection,Reaming,Drilling Formation,Drilling
113,2021-05-12,22:21:20,2021-05-12 22:21:20,15.250000,1120.00,1120.00,2.12,00:15:15,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling
114,2021-05-12,22:36:35,2021-05-12 22:36:35,4.333333,1120.00,1120.00,0.00,,,00:04:20,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling
115,2021-05-12,22:40:55,2021-05-12 22:40:55,64.500000,1127.70,1127.70,7.70,,01:04:30,,NaN,NaN,NaN,NaN,Slide Drilling,Drilling Formation,Drilling
116,2021-05-12,23:45:25,2021-05-12 23:45:25,8.166667,1127.70,1127.70,0.00,,,00:08:10,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling
117,2021-05-12,23:53:35,2021-05-12 23:53:35,113.333333,1147.40,1147.40,19.70,01:53:20,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling
118,2021-05-13,01:46:55,2021-05-13 01:46:55,17.750000,1147.40,1147.40,0.00,,,00:17:45,NaN,NaN,NaN,Pre connection,Reaming,Drilling Formation,Drilling
119,2021-05-13,02:04:40,2021-05-13 02:04:40,5.166667,1147.40,1147.40,29.52,,,,0.083333,03:13:05,05:47:30,Connection,connection,Drilling Formation,Drilling
120,2021-05-13,02:09:50,2021-05-13 02:09:50,8.833333,1147.40,1147.40,0.00,,,00:08:50,NaN,NaN,NaN,Post Connection,Reaming,Drilling Formation,Drilling
121,2021-05-13,02:18:40,2021-05-13 02:18:40,80.600000,1163.32,1163.32,15.92,01:20:36,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling

In [100]:
LabelTest[LabelTest["MajorActivity"]=="Drilling"].head(50)

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Connection Activity,Sub Activity,Activity,MajorActivity,ConnectionTime_Test,Meterage (m) (Drilling)_Test
102,2021-05-12,15:03:40,2021-05-12 15:03:40,26.000000,1092.00,1092.00,4.35,00:26:00,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
103,2021-05-12,15:29:40,2021-05-12 15:29:40,44.000000,1092.00,1092.00,0.00,,,00:44:00,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
104,2021-05-12,16:13:40,2021-05-12 16:13:40,8.333333,1092.00,1092.00,0.00,,,,0.133333,NaN,NaN,NaN,connection,Drilling Formation,Drilling,NaN,NaN
105,2021-05-12,16:22:00,2021-05-12 16:22:00,33.666667,1092.00,1092.00,0.00,,,,NaN,NaN,NaN,NaN,Pressure Test,Drilling Formation,Drilling,NaN,NaN
106,2021-05-12,16:55:40,2021-05-12 16:55:40,84.333333,1092.00,1092.00,0.00,,,,NaN,NaN,NaN,NaN,Stationary,Stationary,Drilling,NaN,NaN
107,2021-05-12,18:20:00,2021-05-12 18:20:00,4.250000,1092.00,1092.00,0.00,,,,0.066667,NaN,NaN,NaN,connection,Drilling Formation,Drilling,NaN,NaN
108,2021-05-12,18:24:15,2021-05-12 18:24:15,13.916667,1092.06,1092.06,0.00,,,00:13:55,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
109,2021-05-12,18:38:10,2021-05-12 18:38:10,197.000000,1117.88,1117.88,25.82,03:17:00,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
110,2021-05-12,21:55:10,2021-05-12 21:55:10,16.750000,1117.88,1117.88,0.00,,,00:16:45,NaN,NaN,NaN,Pre connection,Reaming,Drilling Formation,Drilling,NaN,NaN
111,2021-05-12,22:11:55,2021-05-12 22:11:55,5.250000,1117.88,1117.88,25.82,,,,0.083333,03:17:00,05:47:40,Connection,connection,Drilling Formation,Drilling,NaN,30.17
112,2021-05-12,22:17:10,2021-05-12 22:17:10,4.166667,1117.88,1117.88,0.00,,,00:04:10,NaN,NaN,NaN,Post Connection,Reaming,Drilling Formation,Drilling,NaN,NaN
113,2021-05-12,22:21:20,2021-05-12 22:21:20,15.250000,1120.00,1120.00,2.12,00:15:15,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
114,2021-05-12,22:36:35,2021-05-12 22:36:35,4.333333,1120.00,1120.00,0.00,,,00:04:20,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
115,2021-05-12,22:40:55,2021-05-12 22:40:55,64.500000,1127.70,1127.70,7.70,,01:04:30,,NaN,NaN,NaN,NaN,Slide Drilling,Drilling Formation,Drilling,NaN,NaN
116,2021-05-12,23:45:25,2021-05-12 23:45:25,8.166667,1127.70,1127.70,0.00,,,00:08:10,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
117,2021-05-12,23:53:35,2021-05-12 23:53:35,113.333333,1147.40,1147.40,19.70,01:53:20,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
118,2021-05-13,01:46:55,2021-05-13 01:46:55,17.750000,1147.40,1147.40,0.00,,,00:17:45,NaN,NaN,NaN,Pre connection,Reaming,Drilling Formation,Drilling,NaN,NaN
119,2021-05-13,02:04:40,2021-05-13 02:04:40,5.166667,1147.40,1147.40,29.52,,,,0.083333,03:13:05,05:47:30,Connection,connection,Drilling Formation,Drilling,NaN,29.52
120,2021-05-13,02:09:50,2021-05-13 02:09:50,8.833333,1147.40,1147.40,0.00,,,00:08:50,NaN,NaN,NaN,Post Connection,Reaming,Drilling Formation,Drilling,NaN,NaN
121,2021-05-13,02:18:40,2021-05-13 02:18:40,80.600000,1163.32,1163.32,15.92,01:20:36,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
122,2021-05-13,03:39:16,2021-05-13 03:39:16,39.583333,1163.32,1163.32,0.00,,,00:39:35,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
123,2021-05-13,04:18:51,2021-05-13 04:18:51,9.583333,1163.32,1146.00,0.00,,,,0.150000,NaN,NaN,NaN,connection,Trip Out,Drilling,NaN,NaN
124,2021-05-13,04:28:26,2021-05-13 04:28:26,5.166667,1163.32,1146.00,0.00,,,,NaN,NaN,NaN,NaN,Moving,Trip Out,Drilling,NaN,NaN
125,2021-05-13,04:33:36,2021-05-13 04:33:36,10.083333,1163.32,1116.00,0.00,,,,0.166667,NaN,NaN,NaN,connection,Trip Out,Drilling,NaN,NaN
126,2021-05-13,04:43:41,2021-05-13 04:43:41,12.166667,1163.32,1086.00,0.00,,,,NaN,NaN,NaN,NaN,Moving,Trip Out,Drilling,NaN,NaN
127,2021-05-13,04:55:51,2021-05-13 04:55:51,7.666667,1163.32,1086.00,0.00,,,,0.116667,NaN,NaN,NaN,connection,Trip Out,Drilling,NaN,NaN
128,2021-05-13,05:03:31,2021-05-13 05:03:31,466.200000,1163.32,1086.00,0.00,,,,NaN,NaN,NaN,NaN,Stationary,Stationary,Drilling,NaN,NaN
129,2021-05-13,12:49:43,2021-05-13 12:49:43,4.666667,1163.32,1088.67,0.00,,,,0.066667,NaN,NaN,NaN,connection,Trip In,Drilling,NaN,NaN
130,2021-05-13,12:54:23,2021-05-13 12:54:23,4.666667,1163.32,1088.31,0.00,,,,NaN,NaN,NaN,NaN,Moving,Trip In,Drilling,NaN,NaN
131,2021-05-13,12:59:03,2021-05-13 12:59:03,5.333333,1163.32,1118.47,0.00,,,,0.083333,NaN,NaN,NaN,connection,Trip In,Drilling,NaN,NaN
132,2021-05-13,13:04:23,2021-05-13 13:04:23,4.333333,1163.32,1118.23,0.00,,,,NaN,NaN,NaN,NaN,Moving,Trip In,Drilling,NaN,NaN
133,2021-05-13,13:08:43,2021-05-13 13:08:43,3.333333,1163.32,1147.54,0.00,,,,0.050000,NaN,NaN,NaN,connection,Trip In,Drilling,NaN,NaN
134,2021-05-13,13:12:03,2021-05-13 13:12:03,9.950000,1163.32,1147.54,0.00,,,,NaN,NaN,NaN,NaN,Moving,Trip In,Drilling,NaN,NaN
135,2021-05-13,13:22:00,2021-05-13 13:22:00,5.550000,1163.32,1163.00,0.00,,,00:05:33,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
136,2021-05-13,13:27:33,2021-05-13 13:27:33,69.500000,1176.81,1176.81,13.49,01:09:30,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
137,2021-05-13,14:37:03,2021-05-13 14:37:03,13.333333,1176.81,1176.81,0.00,,,00:13:20,NaN,NaN,NaN,Pre Connection,Reaming,Drilling Formation,Drilling,NaN,NaN
138,2021-05-13,14:50:23,2021-05-13 14:50:23,6.333333,1176.81,1176.81,29.41,,,,0.100000,02:30:06,21:13:24,Connection,connection,Drilling Formation,Drilling,NaN,29.41
139,2021-05-13,14:56:43,2021-05-13 14:56:43,4.166667,1176.81,1176.81,0.00,,,00:04:10,NaN,NaN,NaN,Post Connection,Reaming,Drilling Formation,Drilling,NaN,NaN
140,2021-05-13,15:00:53,2021-05-13 15:00:53,11.416667,1179.00,1179.00,2.19,00:11:25,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
141,2021-05-13,15:12:18,2021-05-13 15:12:18,3.583333,1179.00,1179.00,0.00,,,00:03:35,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
142,2021-05-13,15:15:53,2021-05-13 15:15:53,19.000000,1183.00,1183.00,4.00,,00:19:00,,NaN,NaN,NaN,NaN,Slide Drilling,Drilling Formation,Drilling,NaN,NaN
143,2021-05-13,15:34:53,2021-05-13 15:34:53,3.583333,1183.00,1183.00,0.00,,,00:03:35,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
144,2021-05-13,15:38:28,2021-05-13 15:38:28,7.166667,1184.02,1184.02,1.02,,00:07:10,,NaN,NaN,NaN,NaN,Slide Drilling,Drilling Formation,Drilling,NaN,NaN
145,2021-05-13,15:45:38,2021-05-13 15:45:38,1.083333,1184.02,1184.02,0.00,,,00:01:05,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
146,2021-05-13,15:46:43,2021-05-13 15:46:43,17.166667,1186.51,1186.51,2.49,,00:17:10,,NaN,NaN,NaN,NaN,Slide Drilling,Drilling Formation,Drilling,NaN,NaN
147,2021-05-13,16:03:53,2021-05-13 16:03:53,7.750000,1186.51,1186.51,0.00,,,00:07:45,NaN,NaN,NaN,NaN,Reaming,Drilling Formation,Drilling,NaN,NaN
148,2021-05-13,16:11:38,2021-05-13 16:11:38,89.166667,1206.30,1206.30,19.79,01:29:10,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation,Drilling,NaN,NaN
149,2021-05-13,17:40:48,2021-05-13 17:40:48,13.083333,1206.30,1206.30,0.00,,,00:13:05,NaN,NaN,NaN,Pre connection,Reaming,Drilling Formation,Drilling,NaN,NaN
150,2021-05-13,17:53:53,2021-05-13 17:53:53,3.416667,1206.30,1206.30,23.30,,,,0.050000,01:53:30,03:53:35,Connection,connection,Drilling Formation,Drilling,NaN,29.49
151,2021-05-13,17:57:18,2021-05-13 17:57:18,3.833333,1206.30,1206.30,0.00,,,00:03:50,NaN,NaN,NaN,Post Connection,Reaming,Drilling Formation,Drilling,NaN,NaN

In [103]:
NAMETES = [
    "Cementing Job",
    "Circulation",
    "Connection",
    "Lay Down BHA",
    "Make Up BHA",
    "Moving",
    "Other",
    "Reaming",
    "Rig Repair",
    "Rotary Drilling",
    "Running Casing In",
    "Slide Drilling",
    "Slip and Cut"
    "Stationary",
    "Wait on Cement",
    "Pressure Test",
    "Wash Up",
    "Wash Down",
    "Working Pipe",
    "==========",
    "Cementing Job",
    "Circulate Hole Cleaning",
    "Connection",
    "Drill Out Cement",
    "Drilling Formation",
    "Lay Down BHA",
    "Make up BHA",
    "NPT",
    "Other",
    "Running Casing In",
    "Stationary",
    "Stuck Pipe",
    "Trip In",
    "Trip Out",
    "Wait on Cement",
    "Circulation",
    "Rig Repair",
]
NAMETES

['Cementing Job',
 'Circulation',
 'Connection',
 'Lay Down BHA',
 'Make Up BHA',
 'Moving',
 'Other',
 'Reaming',
 'Rig Repair',
 'Rotary Drilling',
 'Running Casing In',
 'Slide Drilling',
 'Slip and CutStationary',
 'Wait on Cement',
 'Pressure Test',
 'Wash Up',
 'Wash Down',
 'Working Pipe',
 '==========',
 'Cementing Job',
 'Circulate Hole Cleaning',
 'Connection',
 'Drill Out Cement',
 'Drilling Formation',
 'Lay Down BHA',
 'Make up BHA',
 'NPT',
 'Other',
 'Running Casing In',
 'Stationary',
 'Stuck Pipe',
 'Trip In',
 'Trip Out',
 'Wait on Cement',
 'Circulation',
 'Rig Repair']

In [110]:
out_ist = [x.upper() for x in NAMETES]

In [112]:
out_ist

['CEMENTING JOB',
 'CIRCULATION',
 'CONNECTION',
 'LAY DOWN BHA',
 'MAKE UP BHA',
 'MOVING',
 'OTHER',
 'REAMING',
 'RIG REPAIR',
 'ROTARY DRILLING',
 'RUNNING CASING IN',
 'SLIDE DRILLING',
 'SLIP AND CUTSTATIONARY',
 'WAIT ON CEMENT',
 'PRESSURE TEST',
 'WASH UP',
 'WASH DOWN',
 'WORKING PIPE',
 '==========',
 'CEMENTING JOB',
 'CIRCULATE HOLE CLEANING',
 'CONNECTION',
 'DRILL OUT CEMENT',
 'DRILLING FORMATION',
 'LAY DOWN BHA',
 'MAKE UP BHA',
 'NPT',
 'OTHER',
 'RUNNING CASING IN',
 'STATIONARY',
 'STUCK PIPE',
 'TRIP IN',
 'TRIP OUT',
 'WAIT ON CEMENT',
 'CIRCULATION',
 'RIG REPAIR']