In [1]:
import pandas as pd

In [26]:
import glob

list_WITS_file = glob.glob("Data\\raw_wits\\*.csv")



end_time = []
start_time = []
filename = []
TotalRow = []
TotalColumns = [] 

for i in list_WITS_file:
    df_temp = pd.read_csv(i, delimiter='\t')
    # print(df_temp.columns)
    # print((df_temp.reset_index().iloc[:,1].max()))
    # print((df_temp.reset_index().iloc[:,1].min()))
    # print((df_temp.describe().loc[['min', 'max'],[0]]))
    # print(i.split("\\")[-1])
    # TotalRow.append(df_temp.shape)
    # print(df_temp.shape)
    TotalRow.append(df_temp.shape[0])
    TotalColumns.append(df_temp.shape[1])

    end_time.append((df_temp.reset_index().iloc[:,1].max()))
    start_time.append((df_temp.reset_index().iloc[:,1].min()))
    filename.append(i.split("\\")[-1])


    # break

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (188) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [29]:
dict_temp = {
    'filename'  :filename,
    'end_time' : end_time,
    'start_time' : start_time,
    'TotalRow':TotalRow,
    'TotalColumns':TotalColumns
}
# end_time = []
# start_time = []
# filename = []
    
df_out = pd.DataFrame(dict_temp)
df_out

,filename,end_time,start_time,TotalRow,TotalColumns
0,AAE-03.csv,2021-05-27 09:04:00,2021-04-26 12:58:07,21107,209
1,SMP AA 02.csv,2021-08-03 23:33:58,2021-06-19 08:08:11,22075,209
2,SMP AA 03.csv,2021-05-09 17:42:33,2021-04-17 10:20:11,15367,209
3,SMP AA 1.csv,2021-06-10 03:08:43,2021-05-23 08:02:42,5403,209
4,SMP AAE 02.csv,2021-07-13 07:38:25,2021-06-04 09:11:28,20522,209
5,SMP AAE 05.csv,2021-08-09 06:49:09,2021-07-14 16:26:50,24476,209
6,SMP AAE 06 ST 2.csv,2021-12-29 09:39:54,2021-12-14 03:45:15,5869,209
7,SMP AAE 06.csv,2021-09-10 02:39:54,2021-08-15 16:23:15,24651,209
8,SMP AAE 07 ST 1.csv,2021-10-30 08:18:08,2021-10-27 02:26:07,3362,209
9,SMP AAE 07 ST 2.csv,2021-11-24 08:31:30,2021-11-04 05:48:13,3406,209
10,SMP AAE 07 ST 3.csv,2021-12-04 06:02:39,2021-11-23 17:43:17,6001,209
11,SMP AAE 07.csv,2021-10-20 09:21:25,2021-09-29 17:23:52,16899,209
12,SMP AAE-06 ST 1.csv,2021-09-21 09:05:54,2021-08-15 16:23:15,16835,209
13,SMP P 118 ST.csv,2021-03-26 05:26:27,2021-01-06 17:05:09,23431,209
14,SMP_119.csv,2020-12-29 03:05:54,2020-11-30 16:24:42,19913,209

In [34]:
list_RAW_BM_file = glob.glob("Data\\raw_BM\\*.csv")
end_time = []
start_time = []
filename = []
TotalRow = []
TotalColumns = [] 

for i in list_RAW_BM_file:
    print(i)
    df_temp = pd.read_csv(i)

    TotalRow.append(df_temp.shape[0])
    TotalColumns.append(df_temp.shape[1])

    end_time.append((df_temp.reset_index().iloc[:,1].max()))
    start_time.append((df_temp.reset_index().iloc[:,1].min()))
    filename.append(i.split("\\")[-1])

    # print(start_time + end_time + filename)
    # break

Data\raw_BM\ASCII AAE-02 Drilling.csv
Data\raw_BM\ASCII AAE-02 Trip in.csv
Data\raw_BM\ASCII AAE-05 Drilling.csv
Data\raw_BM\ASCII AAE-05 Trip in.csv
Data\raw_BM\ASCII AAE-06 Drilling.csv
Data\raw_BM\ASCII AAE-06 Trip in.csv
Data\raw_BM\ASCII AAE-06ST Drilling.csv
Data\raw_BM\ASCII AAE-06ST1 Trip in.csv
Data\raw_BM\ASCII AAE-06ST2 Drilling.csv
Data\raw_BM\ASCII AAE-06ST2 Trip in.csv
Data\raw_BM\ASCII AAE-07 Drilling.csv
Data\raw_BM\ASCII AAE-07 Trip in.csv
Data\raw_BM\ASCII AAE-07ST Drilling.csv
Data\raw_BM\ASCII AAE-07ST3 Drilling.csv
Data\raw_BM\ASCII AAE-07ST3 Trip in.csv

In [35]:
dict_temp = {
    'filename'  :filename,
    'end_time' : end_time,
    'start_time' : start_time,
    'TotalRow':TotalRow,
    'TotalColumns':TotalColumns
}
# end_time = []
# start_time = []
# filename = []
    
df_out = pd.DataFrame(dict_temp)
df_out

,filename,end_time,start_time,TotalRow,TotalColumns
0,ASCII AAE-02 Drilling.csv,6/24/2021 7:39,6/18/2021 10:00,97478,13
1,ASCII AAE-02 Trip in.csv,6/18/2021 6:59,6/17/2021 0:00,22043,10
2,ASCII AAE-05 Drilling.csv,8/2/2021 2:59,7/28/2021 10:00,76058,13
3,ASCII AAE-05 Trip in.csv,7/28/2021 9:59,7/28/2021 0:30,10760,10
4,ASCII AAE-06 Drilling.csv,8/29/2021 1:00,8/22/2021 10:00,114832,13
5,ASCII AAE-06 Trip in.csv,8/22/2021 8:59,8/22/2021 0:00,6368,10
6,ASCII AAE-06ST Drilling.csv,9/21/2021 9:00,9/18/2021 12:30,48327,13
7,ASCII AAE-06ST1 Trip in.csv,9/18/2021 9:59,9/17/2021 21:00,14708,10
8,ASCII AAE-06ST2 Drilling.csv,12/25/2021 7:59,12/17/2021 20:00,129242,13
9,ASCII AAE-06ST2 Trip in.csv,12/17/2021 20:59,12/17/2021 14:00,4986,10
10,ASCII AAE-07 Drilling.csv,10/20/2021 9:59,10/18/2021 10:00,36776,13
11,ASCII AAE-07 Trip in.csv,10/18/2021 7:39,10/17/2021 10:00,20989,10
12,ASCII AAE-07ST Drilling.csv,10/26/2021 21:25,10/26/2021 20:28,655,13
13,ASCII AAE-07ST3 Drilling.csv,11/30/2021 5:59,11/26/2021 17:50,52020,13
14,ASCII AAE-07ST3 Trip in.csv,11/26/2021 9:59,11/22/2021 10:00,76385,10